import { ChallengeQuestion, BotProfile, BattleDifficulty } from './challengeTypes.ts';

export const BOT_PROFILES: Record<BattleDifficulty, BotProfile> = {
  easy: {
    name: 'Novice Bot',
    title: 'First-Year Cadet',
    difficulty: 'easy',
    accuracyRate: 0.65,
    minDelayMs: 7000,
    maxDelayMs: 12000,
  },
  medium: {
    name: 'Scholar Bot',
    title: 'Undergraduate Topper',
    difficulty: 'medium',
    accuracyRate: 0.85,
    minDelayMs: 4000,
    maxDelayMs: 7500,
  },
  hard: {
    name: 'Grandmaster Bot',
    title: 'Numerical Engine Specialist',
    difficulty: 'hard',
    accuracyRate: 0.96,
    minDelayMs: 2500,
    maxDelayMs: 4500,
  },
};

export const CHALLENGE_QUESTIONS: ChallengeQuestion[] = [
  {
    id: 'cq-1',
    topic: 'bisection',
    question: 'In the Bisection method on interval [a, b], what is the formula for the first approximation x₁?',
    type: 'multiple_choice',
    options: ['(a + b) / 2', '(a · b) / 2', '[a·f(b) - b·f(a)] / [f(b) - f(a)]', 'a - f(a)/f\'(a)'],
    correctAnswer: '(a + b) / 2',
    explanation: 'Bisection repeatedly bisects (halves) the interval: x = (a + b) / 2.',
  },
  {
    id: 'cq-2',
    topic: 'bisection',
    question: 'If f(1) = -3 and f(2) = 5, what is the midpoint x₁ calculated by Bisection?',
    type: 'numeric',
    correctAnswer: '1.5',
    tolerance: 0.01,
    explanation: 'x₁ = (1 + 2) / 2 = 1.5.',
  },
  {
    id: 'cq-3',
    topic: 'false-position',
    question: 'In the False Position chord formula, what is the denominator?',
    type: 'multiple_choice',
    options: ['f(b) - f(a)', 'b - a', 'f\'(x_n)', 'f(a) + f(b)'],
    correctAnswer: 'f(b) - f(a)',
    explanation: 'The chord formula is x = [a·f(b) - b·f(a)] / [f(b) - f(a)].',
  },
  {
    id: 'cq-4',
    topic: 'false-position',
    question: 'In Regula Falsi, if f(a) < 0, f(b) > 0, and f(x₁) < 0, which endpoint is replaced by x₁?',
    type: 'multiple_choice',
    options: ['Endpoint a', 'Endpoint b', 'Both endpoints', 'Neither endpoint'],
    correctAnswer: 'Endpoint a',
    explanation: 'f(x₁) has the same sign as f(a) (both negative), so x₁ replaces a to preserve opposite signs.',
  },
  {
    id: 'cq-5',
    topic: 'newton-raphson',
    question: 'What is the first derivative f\'(x) of f(x) = x³ - 2x - 5?',
    type: 'multiple_choice',
    options: ['3x² - 2', '3x² + 2', 'x² - 2', '3x - 2'],
    correctAnswer: '3x² - 2',
    explanation: 'd/dx (x³ - 2x - 5) = 3x² - 2.',
  },
  {
    id: 'cq-6',
    topic: 'newton-raphson',
    question: 'If f(2) = -1 and f(3) = 16, which endpoint is chosen as x₀ according to the course rule?',
    type: 'multiple_choice',
    options: ['x₀ = 2', 'x₀ = 3', 'x₀ = 2.5', 'Either endpoint arbitrarily'],
    correctAnswer: 'x₀ = 2',
    explanation: 'The course rule specifies |f(x₀)| = min(|f(a)|, |f(b)|). Since |-1| < |16|, x₀ = 2.',
  },
  {
    id: 'cq-7',
    topic: 'newton-raphson',
    question: 'What is the theoretical order of convergence of the Newton-Raphson method for a simple root?',
    type: 'multiple_choice',
    options: ['2 (Quadratic)', '1 (Linear)', '3 (Cubic)', '1.618 (Superlinear)'],
    correctAnswer: '2 (Quadratic)',
    explanation: 'Newton-Raphson has second-order (quadratic) convergence, roughly doubling correct digits every step.',
  },
  {
    id: 'cq-8',
    topic: 'bisection',
    question: 'Does the Bisection method require computing the derivative of f(x)?',
    type: 'multiple_choice',
    options: ['No', 'Yes', 'Only at initial bracket', 'Only if f(x) is transcendental'],
    correctAnswer: 'No',
    explanation: 'Bisection only evaluates function values f(x), requiring no derivatives.',
  },
  {
    id: 'cq-9',
    topic: 'newton-raphson',
    question: 'In Newton-Raphson, what failure occurs if f\'(x_n) = 0 at the current point?',
    type: 'multiple_choice',
    options: [
      'Division by zero (tangent is horizontal)',
      'Method converges instantly',
      'The sign of f(x) reverses',
      'The interval brackets expand',
    ],
    correctAnswer: 'Division by zero (tangent is horizontal)',
    explanation: 'If f\'(x_n) = 0, the tangent line is horizontal and cannot intersect the x-axis, creating division by zero.',
  },
  {
    id: 'cq-10',
    topic: 'theory',
    question: 'Which fundamental theorem guarantees that continuous f(x) has a root in (a, b) when f(a)·f(b) < 0?',
    type: 'multiple_choice',
    options: [
      'Intermediate Value Theorem',
      'Rolle\'s Theorem',
      'Mean Value Theorem',
      'Taylor\'s Theorem',
    ],
    correctAnswer: 'Intermediate Value Theorem',
    explanation: 'The Intermediate Value Theorem guarantees continuous curves passing between negative and positive values cross the x-axis.',
  },
  {
    id: 'cq-11',
    topic: 'newton-raphson',
    question: 'Given x₀ = 2, f(2) = 4, and f\'(2) = 31, calculate x₁ to 3 decimal places.',
    type: 'numeric',
    correctAnswer: '1.871',
    tolerance: 0.005,
    explanation: 'x₁ = 2 - (4 / 31) = 2 - 0.129 = 1.871 (Primary Course Example).',
  },
  {
    id: 'cq-12',
    topic: 'false-position',
    question: 'Given a = 1, b = 2, f(1) = -1, f(2) = 5, what is False Position x₁ = (1·5 - 2·(-1))/(5 - (-1))?',
    type: 'numeric',
    correctAnswer: '1.167',
    tolerance: 0.01,
    explanation: 'x₁ = (5 + 2) / 6 = 7/6 ≈ 1.1667.',
  },
  {
    id: 'cq-13',
    topic: 'theory',
    question: 'Is the Newton-Raphson method an open method or a bracketing method?',
    type: 'multiple_choice',
    options: ['Open method', 'Bracketing method', 'Fixed interval method', 'None of these'],
    correctAnswer: 'Open method',
    explanation: 'Newton-Raphson does not maintain bracket bounds [a, b]; it steps freely from point to point using tangents.',
  },
  {
    id: 'cq-14',
    topic: 'false-position',
    question: 'Can the False Position method pin one endpoint while moving only the other for convex/concave curves?',
    type: 'multiple_choice',
    options: ['Yes', 'No', 'Never in polynomials', 'Only for linear functions'],
    correctAnswer: 'Yes',
    explanation: 'Due to curve convexity, one endpoint often remains fixed (pinned) while the other steps progressively inward.',
  },
  {
    id: 'cq-15',
    topic: 'newton-raphson',
    question: 'For f(x) = x² - 5, what is the Newton-Raphson iterative formula for x_(n+1)?',
    type: 'multiple_choice',
    options: [
      '(x_n + 5/x_n) / 2',
      'x_n - (x_n² - 5)',
      '(x_n - 5/x_n) / 2',
      'x_n / 2 + 5',
    ],
    correctAnswer: '(x_n + 5/x_n) / 2',
    explanation: 'x_(n+1) = x_n - (x_n² - 5)/(2x_n) = (2x_n² - x_n² + 5)/(2x_n) = (x_n + 5/x_n)/2 (Heron\'s formula).',
  },
];
